#http_port: 8123
#tcp_port: 9000
#interserver_http_port: 9009
#interserver_http_host: clickhouse-node1
#listen_host: 0.0.0.0

#max_connections: 4096
#keep_alive_timeout: 3
#max_concurrent_queries: 100
#uncompressed_cache_size: 8589934592
#mark_cache_size: 5368709120

#default_profile: default
#default_database: default
#timezone: Europe/Moscow
#mlock_executable: false

#user_directories:
#    users_xml:
#        path: users.yaml
#    local_directory:
#        path: /var/lib/clickhouse/access/

#remote_servers:
#    main_cluster:
#        shard:
#            -   internal_replication: false
#                replica:
#                    -   host: clickhouse-node1
#                        default_database: shard
#                        port: 9000
#                    -   host: clickhouse-node2
#                        default_database: replica
#                        port: 9000

#zookeeper:
#    node:
#        "@index": "1"
#        host: example1
#        port: 2181

#macros:
#    cluster: main_cluster

#builtin_dictionaries_reload_interval: 3600
#max_session_timeout: 3600
#default_session_timeout: 60

#path: /var/lib/clickhouse/
#tmp_path: /var/lib/clickhouse/tmp/
#user_files_path: /var/lib/clickhouse/user_files/
#format_schema_path: /var/lib/clickhouse/format_schemas/
#distributed_ddl:
#    path: /clickhouse/task_queue/ddl

#logger:
#    level: debug
#    log: /var/log/clickhouse-server/clickhouse-server.log
#    errorlog: /var/log/clickhouse-server/clickhouse-server.err.log
#    size: 1000M
#    count: 10

#query_log:
#    database: system
#    table: query_log
#    partition_by: toYYYYMM(event_date)
#    ttl: 'event_date + INTERVAL 30 DAY DELETE'
#    flush_interval_milliseconds: 7500

#trace_log:
#    database: system
#    table: trace_log
#    partition_by: toYYYYMM(event_date)
#    ttl: 'event_date + INTERVAL 30 DAY DELETE'
#    flush_interval_milliseconds: 7500
