# A complete example of a real configuration written in YAML:
# https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/users.yaml.example

#profiles:
#    default:
#        max_memory_usage: 10000000000
#        use_uncompressed_cache: 0
#        load_balancing: in_order
#        log_queries: 1

users:
    default:
        password:
        networks:
            ip: '::/0'
        profile: default
        quota: default

quotas:
    default:
        interval:
            duration: 3600
            queries: 0
            errors: 0
            result_rows: 0
            read_rows: 0
            execution_time: 0
